[2023-06-13 16:40:23,082] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:40:21.242441+00:00 [queued]>
[2023-06-13 16:40:23,099] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:40:21.242441+00:00 [queued]>
[2023-06-13 16:40:23,100] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-13 16:40:23,101] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-13 16:40:23,101] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-13 16:40:23,111] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-06-13T16:40:21.242441+00:00
[2023-06-13 16:40:23,115] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2023-06-13 16:40:23,118] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', '2023-06-13T16:40:21.242441+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmprsslf2pn', '--error-file', '/tmp/tmp4ssxdmxu']
[2023-06-13 16:40:23,120] {standard_task_runner.py:77} INFO - Job 78: Subtask load_seed_data_once
[2023-06-13 16:40:23,160] {logging_mixin.py:104} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:40:21.242441+00:00 [running]> on host 368d21ccb808
[2023-06-13 16:40:23,214] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T16:40:21.242441+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T16:40:21.242441+00:00
[2023-06-13 16:40:23,216] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-13 16:40:23,217] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2023-06-13 16:40:23,224] {subprocess.py:74} INFO - Output:
[2023-06-13 16:40:24,836] {subprocess.py:78} INFO - Running with dbt=0.19.0
[2023-06-13 16:40:26,819] {subprocess.py:78} INFO - Encountered an error while reading the project:
[2023-06-13 16:40:26,819] {subprocess.py:78} INFO -   ERROR: Runtime Error
[2023-06-13 16:40:26,820] {subprocess.py:78} INFO -   at path []: Additional properties are not allowed ('model-paths', 'seed-paths' were unexpected)
[2023-06-13 16:40:26,821] {subprocess.py:78} INFO - 
[2023-06-13 16:40:26,821] {subprocess.py:78} INFO - Error encountered in /dbt/dbt_project.yml
[2023-06-13 16:40:26,822] {subprocess.py:78} INFO - Encountered an error:
[2023-06-13 16:40:26,822] {subprocess.py:78} INFO - Runtime Error
[2023-06-13 16:40:26,823] {subprocess.py:78} INFO -   Could not run dbt
[2023-06-13 16:40:27,056] {subprocess.py:82} INFO - Command exited with return code 2
[2023-06-13 16:40:27,068] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2023-06-13 16:40:27,070] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230613T164021, start_date=20230613T164023, end_date=20230613T164027
[2023-06-13 16:40:27,149] {local_task_job.py:149} INFO - Task exited with return code 1
