[2023-06-13 16:13:58,680] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:13:57.724924+00:00 [queued]>
[2023-06-13 16:13:58,690] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:13:57.724924+00:00 [queued]>
[2023-06-13 16:13:58,691] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-13 16:13:58,692] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-13 16:13:58,692] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-13 16:13:58,704] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-06-13T16:13:57.724924+00:00
[2023-06-13 16:13:58,710] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', '2023-06-13T16:13:57.724924+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpf2s3wzdq', '--error-file', '/tmp/tmpt8_xc1ns']
[2023-06-13 16:13:58,712] {standard_task_runner.py:77} INFO - Job 74: Subtask load_seed_data_once
[2023-06-13 16:13:58,708] {standard_task_runner.py:52} INFO - Started process 1242 to run task
[2023-06-13 16:13:58,843] {logging_mixin.py:104} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-13T16:13:57.724924+00:00 [running]> on host 913ca37e2403
[2023-06-13 16:13:58,895] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T16:13:57.724924+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T16:13:57.724924+00:00
[2023-06-13 16:13:58,896] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-13 16:13:58,898] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2023-06-13 16:13:58,903] {subprocess.py:74} INFO - Output:
[2023-06-13 16:14:00,783] {subprocess.py:78} INFO - Running with dbt=0.19.0
[2023-06-13 16:14:02,788] {subprocess.py:78} INFO - Encountered an error while reading the project:
[2023-06-13 16:14:02,789] {subprocess.py:78} INFO -   ERROR: Runtime Error
[2023-06-13 16:14:02,789] {subprocess.py:78} INFO -   at path []: Additional properties are not allowed ('model-paths', 'seed-paths' were unexpected)
[2023-06-13 16:14:02,790] {subprocess.py:78} INFO - 
[2023-06-13 16:14:02,790] {subprocess.py:78} INFO - Error encountered in /dbt/dbt_project.yml
[2023-06-13 16:14:02,791] {subprocess.py:78} INFO - Encountered an error:
[2023-06-13 16:14:02,791] {subprocess.py:78} INFO - Runtime Error
[2023-06-13 16:14:02,792] {subprocess.py:78} INFO -   Could not run dbt
[2023-06-13 16:14:03,063] {subprocess.py:82} INFO - Command exited with return code 2
[2023-06-13 16:14:03,073] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2023-06-13 16:14:03,075] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230613T161357, start_date=20230613T161358, end_date=20230613T161403
[2023-06-13 16:14:03,122] {local_task_job.py:149} INFO - Task exited with return code 1
