[2023-06-08 10:18:00,379] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T10:17:58.731867+00:00 [queued]>
[2023-06-08 10:18:00,394] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T10:17:58.731867+00:00 [queued]>
[2023-06-08 10:18:00,395] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 10:18:00,396] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-08 10:18:00,396] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 10:18:00,413] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-06-08T10:17:58.731867+00:00
[2023-06-08 10:18:00,417] {standard_task_runner.py:52} INFO - Started process 263 to run task
[2023-06-08 10:18:00,421] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', '2023-06-08T10:17:58.731867+00:00', '--job-id', '22', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpknfddlqz', '--error-file', '/tmp/tmpjm29pm5z']
[2023-06-08 10:18:00,423] {standard_task_runner.py:77} INFO - Job 22: Subtask load_seed_data_once
[2023-06-08 10:18:00,473] {logging_mixin.py:104} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T10:17:58.731867+00:00 [running]> on host 1e9c7bef4812
[2023-06-08 10:18:00,543] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T10:17:58.731867+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-08T10:17:58.731867+00:00
[2023-06-08 10:18:00,545] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-08 10:18:00,546] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /Airflow_DBT_Snowflake && dbt seed --profiles-dir .']
[2023-06-08 10:18:00,559] {subprocess.py:74} INFO - Output:
[2023-06-08 10:18:00,562] {subprocess.py:78} INFO - bash: line 0: cd: /Airflow_DBT_Snowflake: No such file or directory
[2023-06-08 10:18:00,563] {subprocess.py:82} INFO - Command exited with return code 1
[2023-06-08 10:18:00,579] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2023-06-08 10:18:00,582] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230608T101758, start_date=20230608T101800, end_date=20230608T101800
[2023-06-08 10:18:00,641] {local_task_job.py:149} INFO - Task exited with return code 1
