[2023-06-08 09:12:23,928] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T09:12:22.705576+00:00 [queued]>
[2023-06-08 09:12:23,949] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T09:12:22.705576+00:00 [queued]>
[2023-06-08 09:12:23,950] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 09:12:23,950] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-06-08 09:12:23,951] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-06-08 09:12:23,962] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2023-06-08T09:12:22.705576+00:00
[2023-06-08 09:12:23,968] {standard_task_runner.py:52} INFO - Started process 106 to run task
[2023-06-08 09:12:23,973] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', '2023-06-08T09:12:22.705576+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpq8dnsa03', '--error-file', '/tmp/tmpu_zysi7e']
[2023-06-08 09:12:23,975] {standard_task_runner.py:77} INFO - Job 11: Subtask load_seed_data_once
[2023-06-08 09:12:24,027] {logging_mixin.py:104} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once 2023-06-08T09:12:22.705576+00:00 [running]> on host 1e9c7bef4812
[2023-06-08 09:12:24,090] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T09:12:22.705576+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-08T09:12:22.705576+00:00
[2023-06-08 09:12:24,092] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-06-08 09:12:24,093] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /Airflow_DBT_Snowflake && dbt seed --profiles-dir .']
[2023-06-08 09:12:24,103] {subprocess.py:74} INFO - Output:
[2023-06-08 09:12:24,105] {subprocess.py:78} INFO - bash: line 0: cd: /Airflow_DBT_Snowflake: No such file or directory
[2023-06-08 09:12:24,106] {subprocess.py:82} INFO - Command exited with return code 1
[2023-06-08 09:12:24,120] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2023-06-08 09:12:24,122] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20230608T091222, start_date=20230608T091223, end_date=20230608T091224
[2023-06-08 09:12:24,189] {local_task_job.py:149} INFO - Task exited with return code 1
